// <auto-generated />
using System;
using CP6.Core.Services.ErpIntegration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CP6.Persistence.PostgreSql.Migrations.ErpIntegration
{
    [DbContext(typeof(ErpIntegrationContext))]
    partial class ErpIntegrationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("cp6_ci_as_provider_v1")
                .HasAnnotation("Npgsql:CollationDefinition:cp6_ci_as_provider_v1", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpDeliveryReplayAudit", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("InputRowVersion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("C");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("PreviousAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("C");

                    b.HasKey("TenantId", "OperationId")
                        .HasName("PK_DeliveryReplayAudit")
                        .HasAnnotation("CP6:OriginalName", "PK_DeliveryReplayAudit");

                    b.HasIndex("TenantId", "Kind", "TargetId", "ReplayedAtUtc")
                        .HasDatabaseName("IX_DeliveryReplayAudit_TenantId_Kind_TargetId_ReplayedAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_DeliveryReplayAudit_TenantId_Kind_TargetId_ReplayedAtUtc");

                    b.ToTable("DeliveryReplayAudit", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryReplayAudit_ActorId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ActorId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 100")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_ActorId_Utf16Capacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_InputRowVersion_BinaryCapacity", "octet_length(\"InputRowVersion\") <= 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_InputRowVersion_BinaryCapacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_Kind_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"Kind\"), 'UTF8')) <= 16")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_Kind_Cp936Capacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_ReasonCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ReasonCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_ReasonCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_DeliveryReplayAudit_TargetId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"TargetId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_DeliveryReplayAudit_TargetId_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "DeliveryReplayAudit");
                });

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpInboxReceipt", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("C");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("LastConflictSha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("ReplayReasonCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset?>("RetryAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId")
                        .HasName("PK_CommandInbox")
                        .HasAnnotation("CP6:OriginalName", "PK_CommandInbox");

                    b.HasIndex("TenantId", "Status", "RetryAtUtc")
                        .HasDatabaseName("IX_CommandInbox_TenantId_Status_RetryAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_CommandInbox_TenantId_Status_RetryAtUtc");

                    b.ToTable("CommandInbox", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_CommandInbox_ErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_ErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_EventType_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"EventType\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 200")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_EventType_Utf16Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_LastConflictSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LastConflictSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_LastConflictSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_ReplayReasonCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ReplayReasonCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_ReplayReasonCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_CommandInbox_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_CommandInbox_RowVersion_TokenLength");
                        });

                    b.HasAnnotation("CP6:OriginalName", "CommandInbox");
                });

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpInboxReplayAudit", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("InputRowVersion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("C");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("PreviousAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.HasKey("TenantId", "OperationId")
                        .HasName("PK_InboxReplayAudit")
                        .HasAnnotation("CP6:OriginalName", "PK_InboxReplayAudit");

                    b.HasIndex("TenantId", "MessageId", "ReplayedAtUtc")
                        .HasDatabaseName("IX_InboxReplayAudit_TenantId_MessageId_ReplayedAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_InboxReplayAudit_TenantId_MessageId_ReplayedAtUtc");

                    b.ToTable("InboxReplayAudit", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_InboxReplayAudit_ActorId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ActorId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 100")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_InboxReplayAudit_ActorId_Utf16Capacity");

                            t.HasCheckConstraint("CK_InboxReplayAudit_InputRowVersion_BinaryCapacity", "octet_length(\"InputRowVersion\") <= 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_InboxReplayAudit_InputRowVersion_BinaryCapacity");

                            t.HasCheckConstraint("CK_InboxReplayAudit_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_InboxReplayAudit_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_InboxReplayAudit_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_InboxReplayAudit_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_InboxReplayAudit_ReasonCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ReasonCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_InboxReplayAudit_ReasonCode_Cp936Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "InboxReplayAudit");
                });

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpIntegrationAggregate", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastAggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("LastRequestVersion")
                        .HasColumnType("integer");

                    b.Property<int>("LastResultVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.HasKey("TenantId", "Kind", "AggregateId")
                        .HasName("PK_Aggregate")
                        .HasAnnotation("CP6:OriginalName", "PK_Aggregate");

                    b.ToTable("Aggregate", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_Aggregate_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Aggregate_RowVersion_TokenLength");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Aggregate");
                });

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpIntegrationRequest", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequestVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultDataJson")
                        .IsRequired()
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("ResultVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<bool>("Terminal")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.HasKey("TenantId", "Kind", "AggregateId", "RequestVersion")
                        .HasName("PK_Request")
                        .HasAnnotation("CP6:OriginalName", "PK_Request");

                    b.HasIndex("TenantId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("IX_Request_TenantId_RequestId")
                        .HasAnnotation("CP6:OriginalName", "IX_Request_TenantId_RequestId");

                    b.ToTable("Request", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_Request_InputSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"InputSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Request_InputSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Request_ResultType_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ResultType\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 200")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Request_ResultType_Utf16Capacity");

                            t.HasCheckConstraint("CK_Request_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Request_RowVersion_TokenLength");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Request");
                });

            modelBuilder.Entity("CP6.Core.Services.ErpIntegration.ErpOrderBridgeDispatch", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderKey")
                        .HasMaxLength(20)
                        .HasColumnType("bpchar")
                        .UseCollation("C");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.HasKey("TenantId", "OrderKey")
                        .HasName("PK_OrderBridgeDispatch")
                        .HasAnnotation("CP6:OriginalName", "PK_OrderBridgeDispatch");

                    b.HasIndex("CompletedAtUtc", "AvailableAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_OrderBridgeDispatch_CompletedAtUtc_AvailableAtU_dafc50a86d55")
                        .HasAnnotation("CP6:OriginalName", "IX_OrderBridgeDispatch_CompletedAtUtc_AvailableAtUtc_LeaseExpiresAtUtc");

                    b.ToTable("OrderBridgeDispatch", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_OrderBridgeDispatch_LastErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LastErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_OrderBridgeDispatch_LastErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_OrderBridgeDispatch_LeaseOwner_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LeaseOwner\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_OrderBridgeDispatch_LeaseOwner_Cp936Capacity");

                            t.HasCheckConstraint("CK_OrderBridgeDispatch_OrderKey_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"OrderKey\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 20")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_OrderBridgeDispatch_OrderKey_Utf16Capacity");

                            t.HasCheckConstraint("CK_OrderBridgeDispatch_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_OrderBridgeDispatch_RowVersion_TokenLength");
                        });

                    b.HasAnnotation("CP6:OriginalName", "OrderBridgeDispatch");
                });

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("ReplayReasonCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<string>("SupportReference")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_DeadLetterRecord")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_DeadLetterRecord");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Cp6_DeadLetterRecord_CreatedAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_DeadLetterRecord_CreatedAtUtc");

                    b.HasIndex("Direction", "MessageId", "ConsumerName")
                        .HasDatabaseName("IX_Cp6_DeadLetterRecord_Direction_MessageId_ConsumerName")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_DeadLetterRecord_Direction_MessageId_ConsumerName");

                    b.ToTable("Cp6_DeadLetterRecord", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ConsumerName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ConsumerName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ConsumerName_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ReplayReasonCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ReplayReasonCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ReplayReasonCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_RowVersion_TokenLength");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_SupportReference_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"SupportReference\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_SupportReference_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_DeadLetterRecord");
                });

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("CausationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportReference")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_OutboxMessage")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_OutboxMessage");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cp6_OutboxMessage_MessageId")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_MessageId");

                    b.HasIndex("Status", "AvailableAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_Cp6_OutboxMessage_Status_AvailableAtUtc_LeaseExpiresAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_Status_AvailableAtUtc_LeaseExpiresAtUtc");

                    b.HasIndex("TenantId", "AggregateId", "AggregateVersion")
                        .HasDatabaseName("IX_Cp6_OutboxMessage_TenantId_AggregateId_AggregateVersion")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_TenantId_AggregateId_AggregateVersion");

                    b.ToTable("Cp6_OutboxMessage", "erp_integration", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_AggregateId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"AggregateId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_AggregateId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_CausationId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"CausationId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_CausationId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_CorrelationId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"CorrelationId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_CorrelationId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LastErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LastErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LastErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LeaseOwner_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"LeaseOwner\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LeaseOwner_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LeaseToken_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LeaseToken\"), 'UTF8')) <= 32")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LeaseToken_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_PartitionKey_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"PartitionKey\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 512")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_PartitionKey_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_RowVersion_TokenLength");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_SupportReference_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"SupportReference\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_SupportReference_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_TopicName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"TopicName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 249")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_TopicName_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_OutboxMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
