// <auto-generated />
using System;
using CP6.Core.Services.CrmIdentity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CP6.Persistence.PostgreSql.Migrations.IdentityPriority
{
    [DbContext(typeof(IdentityMessagingContext))]
    [Migration("20261002151342_PostgreSqlIdentityPriorityBaselineV1")]
    partial class PostgreSqlIdentityPriorityBaselineV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("cp6_ci_as_provider_v1")
                .HasAnnotation("Npgsql:CollationDefinition:cp6_ci_as_provider_v1", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("ReplayReasonCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("ReplayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<string>("SupportReference")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_DeadLetterRecord")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_DeadLetterRecord");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Cp6_DeadLetterRecord_CreatedAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_DeadLetterRecord_CreatedAtUtc");

                    b.HasIndex("Direction", "MessageId", "ConsumerName")
                        .HasDatabaseName("IX_Cp6_DeadLetterRecord_Direction_MessageId_ConsumerName")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_DeadLetterRecord_Direction_MessageId_ConsumerName");

                    b.ToTable("Cp6_DeadLetterRecord", "crm_identity_priority", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ConsumerName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ConsumerName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ConsumerName_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_ReplayReasonCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"ReplayReasonCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_ReplayReasonCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_RowVersion_TokenLength");

                            t.HasCheckConstraint("CK_Cp6_DeadLetterRecord_SupportReference_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"SupportReference\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_DeadLetterRecord_SupportReference_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_DeadLetterRecord");
                });

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6InboxAggregateCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_InboxAggregateCheckpoint")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_InboxAggregateCheckpoint");

                    b.HasIndex("ConsumerName", "TenantId", "AggregateId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cp6_InboxAggregateCheckpoint_ConsumerName_Tenan_8bdad6570c8d")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_InboxAggregateCheckpoint_ConsumerName_TenantId_AggregateId");

                    b.ToTable("Cp6_InboxAggregateCheckpoint", "crm_identity_priority", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_InboxAggregateCheckpoint_AggregateId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"AggregateId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxAggregateCheckpoint_AggregateId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxAggregateCheckpoint_ConsumerName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ConsumerName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxAggregateCheckpoint_ConsumerName_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxAggregateCheckpoint_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxAggregateCheckpoint_RowVersion_TokenLength");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_InboxAggregateCheckpoint");
                });

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportReference")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_InboxMessage")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_InboxMessage");

                    b.HasIndex("ConsumerName", "MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cp6_InboxMessage_ConsumerName_MessageId")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_InboxMessage_ConsumerName_MessageId");

                    b.HasIndex("Status", "ProcessedAtUtc")
                        .HasDatabaseName("IX_Cp6_InboxMessage_Status_ProcessedAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_InboxMessage_Status_ProcessedAtUtc");

                    b.ToTable("Cp6_InboxMessage", "crm_identity_priority", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_InboxMessage_AggregateId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"AggregateId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_AggregateId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_ConsumerName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"ConsumerName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_ConsumerName_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_LastErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LastErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_LastErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_OutcomeCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"OutcomeCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_OutcomeCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_PartitionKey_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"PartitionKey\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 512")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_PartitionKey_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_RowVersion_TokenLength");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_SupportReference_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"SupportReference\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_SupportReference_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_InboxMessage_TopicName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"TopicName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 249")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_InboxMessage_TopicName_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_InboxMessage");
                });

            modelBuilder.Entity("CP6.Platform.EntityFramework.Cp6OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("CausationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("LeaseToken")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("CP6:TimeContract", "UtcOffsetZero");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("bytea")
                        .HasAnnotation("CP6:DatabaseToken", true);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportReference")
                        .HasMaxLength(128)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(249)
                        .HasColumnType("bpchar")
                        .UseCollation("cp6_ci_as_provider_v1");

                    b.HasKey("Id")
                        .HasName("PK_Cp6_OutboxMessage")
                        .HasAnnotation("CP6:OriginalName", "PK_Cp6_OutboxMessage");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_Cp6_OutboxMessage_MessageId")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_MessageId");

                    b.HasIndex("Status", "AvailableAtUtc", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_Cp6_OutboxMessage_Status_AvailableAtUtc_LeaseExpiresAtUtc")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_Status_AvailableAtUtc_LeaseExpiresAtUtc");

                    b.HasIndex("TenantId", "AggregateId", "AggregateVersion")
                        .HasDatabaseName("IX_Cp6_OutboxMessage_TenantId_AggregateId_AggregateVersion")
                        .HasAnnotation("CP6:OriginalName", "IX_Cp6_OutboxMessage_TenantId_AggregateId_AggregateVersion");

                    b.ToTable("Cp6_OutboxMessage", "crm_identity_priority", t =>
                        {
                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_AggregateId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"AggregateId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_AggregateId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_CausationId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"CausationId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_CausationId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_CorrelationId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"CorrelationId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_CorrelationId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LastErrorCode_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LastErrorCode\"), 'UTF8')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LastErrorCode_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LeaseOwner_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"LeaseOwner\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LeaseOwner_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_LeaseToken_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"LeaseToken\"), 'UTF8')) <= 32")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_LeaseToken_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_MessageId_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"MessageId\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_MessageId_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_PartitionKey_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"PartitionKey\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 512")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_PartitionKey_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_PayloadSha256_Cp936Capacity", "public.cp6_cp936_length_v1(convert_from(pg_catalog.bpcharsend(\"PayloadSha256\"), 'UTF8')) <= 64")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_PayloadSha256_Cp936Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_RowVersion_TokenLength", "octet_length(\"RowVersion\") = 8")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_RowVersion_TokenLength");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_SupportReference_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"SupportReference\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 128")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_SupportReference_Utf16Capacity");

                            t.HasCheckConstraint("CK_Cp6_OutboxMessage_TopicName_Utf16Capacity", "char_length(regexp_replace((convert_from(pg_catalog.bpcharsend(\"TopicName\"), 'UTF8'))::text COLLATE \"C\", U&'[\\+010000-\\+10FFFF]', 'aa', 'g')) <= 249")
                                .HasAnnotation("CP6:GeneratedCapacity", true)
                                .HasAnnotation("CP6:OriginalName", "CK_Cp6_OutboxMessage_TopicName_Utf16Capacity");
                        });

                    b.HasAnnotation("CP6:OriginalName", "Cp6_OutboxMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
