//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface ISpaceDesignV1Client {

    /**
     * @return OK
     */
    getModel(siteId: string): Promise<SpaceModelDto>;

    /**
     * @param status (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getVersions(siteId: string, status: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceVersionDto>;

    /**
     * @param idempotency_Key Opaque caller key; 1-128 UTF-8 bytes. Reuse with a different request returns SPACE_IDEMPOTENCY_KEY_REUSED.
     * @return Accepted
     */
    createVersion(siteId: string, idempotency_Key: string, body: CreateSpaceVersionRequest): Promise<CreateSpaceVersionResponse>;

    /**
     * @return OK
     */
    getVersion(versionId: string): Promise<SpaceVersionDto>;

    /**
     * @param sourceType (optional)
     * @param state (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getSources(versionId: string, sourceType: string | undefined, state: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceSourceDto>;

    /**
     * @param idempotency_Key Opaque caller key; 1-128 UTF-8 bytes. Reuse with a different request returns SPACE_IDEMPOTENCY_KEY_REUSED.
     * @return Created
     */
    createSource(versionId: string, idempotency_Key: string, body: CreateSpaceSourceRequest): Promise<CreateSpaceSourceResponse>;

    /**
     * @return OK
     */
    getJob(jobId: string): Promise<SpaceJobDto>;

    /**
     * @param severity (optional)
     * @param status (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getIssues(versionId: string, severity: string | undefined, status: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceIssueDto>;
}

export class SpaceDesignV1Client implements ISpaceDesignV1Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getModel(siteId: string): Promise<SpaceModelDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/sites/{siteId}/model";
        if (siteId === undefined || siteId === null)
            throw new globalThis.Error("The parameter 'siteId' must be defined.");
        url_ = url_.replace("{siteId}", encodeURIComponent("" + siteId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetModel(_response);
        });
    }

    protected processGetModel(response: Response): Promise<SpaceModelDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpaceModelDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpaceModelDto>(null as any);
    }

    /**
     * @param status (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getVersions(siteId: string, status: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceVersionDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/sites/{siteId}/versions?";
        if (siteId === undefined || siteId === null)
            throw new globalThis.Error("The parameter 'siteId' must be defined.");
        url_ = url_.replace("{siteId}", encodeURIComponent("" + siteId));
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        if (cursor === null)
            throw new globalThis.Error("The parameter 'cursor' cannot be null.");
        else if (cursor !== undefined)
            url_ += "cursor=" + encodeURIComponent("" + cursor) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetVersions(_response);
        });
    }

    protected processGetVersions(response: Response): Promise<SpacePageOfSpaceVersionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpacePageOfSpaceVersionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpacePageOfSpaceVersionDto>(null as any);
    }

    /**
     * @param idempotency_Key Opaque caller key; 1-128 UTF-8 bytes. Reuse with a different request returns SPACE_IDEMPOTENCY_KEY_REUSED.
     * @return Accepted
     */
    createVersion(siteId: string, idempotency_Key: string, body: CreateSpaceVersionRequest): Promise<CreateSpaceVersionResponse> {
        let url_ = this.baseUrl + "/api/space/design/v1/sites/{siteId}/versions";
        if (siteId === undefined || siteId === null)
            throw new globalThis.Error("The parameter 'siteId' must be defined.");
        url_ = url_.replace("{siteId}", encodeURIComponent("" + siteId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Idempotency-Key": idempotency_Key !== undefined && idempotency_Key !== null ? "" + idempotency_Key : "",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateVersion(_response);
        });
    }

    protected processCreateVersion(response: Response): Promise<CreateSpaceVersionResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 202) {
            return response.text().then((_responseText) => {
            let result202: any = null;
            let resultData202 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result202 = CreateSpaceVersionResponse.fromJS(resultData202);
            return result202;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateSpaceVersionResponse>(null as any);
    }

    /**
     * @return OK
     */
    getVersion(versionId: string): Promise<SpaceVersionDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/versions/{versionId}";
        if (versionId === undefined || versionId === null)
            throw new globalThis.Error("The parameter 'versionId' must be defined.");
        url_ = url_.replace("{versionId}", encodeURIComponent("" + versionId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetVersion(_response);
        });
    }

    protected processGetVersion(response: Response): Promise<SpaceVersionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpaceVersionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpaceVersionDto>(null as any);
    }

    /**
     * @param sourceType (optional)
     * @param state (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getSources(versionId: string, sourceType: string | undefined, state: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceSourceDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/versions/{versionId}/sources?";
        if (versionId === undefined || versionId === null)
            throw new globalThis.Error("The parameter 'versionId' must be defined.");
        url_ = url_.replace("{versionId}", encodeURIComponent("" + versionId));
        if (sourceType === null)
            throw new globalThis.Error("The parameter 'sourceType' cannot be null.");
        else if (sourceType !== undefined)
            url_ += "sourceType=" + encodeURIComponent("" + sourceType) + "&";
        if (state === null)
            throw new globalThis.Error("The parameter 'state' cannot be null.");
        else if (state !== undefined)
            url_ += "state=" + encodeURIComponent("" + state) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        if (cursor === null)
            throw new globalThis.Error("The parameter 'cursor' cannot be null.");
        else if (cursor !== undefined)
            url_ += "cursor=" + encodeURIComponent("" + cursor) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSources(_response);
        });
    }

    protected processGetSources(response: Response): Promise<SpacePageOfSpaceSourceDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpacePageOfSpaceSourceDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpacePageOfSpaceSourceDto>(null as any);
    }

    /**
     * @param idempotency_Key Opaque caller key; 1-128 UTF-8 bytes. Reuse with a different request returns SPACE_IDEMPOTENCY_KEY_REUSED.
     * @return Created
     */
    createSource(versionId: string, idempotency_Key: string, body: CreateSpaceSourceRequest): Promise<CreateSpaceSourceResponse> {
        let url_ = this.baseUrl + "/api/space/design/v1/versions/{versionId}/sources";
        if (versionId === undefined || versionId === null)
            throw new globalThis.Error("The parameter 'versionId' must be defined.");
        url_ = url_.replace("{versionId}", encodeURIComponent("" + versionId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Idempotency-Key": idempotency_Key !== undefined && idempotency_Key !== null ? "" + idempotency_Key : "",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateSource(_response);
        });
    }

    protected processCreateSource(response: Response): Promise<CreateSpaceSourceResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CreateSpaceSourceResponse.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateSpaceSourceResponse>(null as any);
    }

    /**
     * @return OK
     */
    getJob(jobId: string): Promise<SpaceJobDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/jobs/{jobId}";
        if (jobId === undefined || jobId === null)
            throw new globalThis.Error("The parameter 'jobId' must be defined.");
        url_ = url_.replace("{jobId}", encodeURIComponent("" + jobId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetJob(_response);
        });
    }

    protected processGetJob(response: Response): Promise<SpaceJobDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpaceJobDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpaceJobDto>(null as any);
    }

    /**
     * @param severity (optional)
     * @param status (optional)
     * @param limit (optional)
     * @param cursor (optional)
     * @return OK
     */
    getIssues(versionId: string, severity: string | undefined, status: string | undefined, limit: number | undefined, cursor: string | undefined): Promise<SpacePageOfSpaceIssueDto> {
        let url_ = this.baseUrl + "/api/space/design/v1/versions/{versionId}/issues?";
        if (versionId === undefined || versionId === null)
            throw new globalThis.Error("The parameter 'versionId' must be defined.");
        url_ = url_.replace("{versionId}", encodeURIComponent("" + versionId));
        if (severity === null)
            throw new globalThis.Error("The parameter 'severity' cannot be null.");
        else if (severity !== undefined)
            url_ += "severity=" + encodeURIComponent("" + severity) + "&";
        if (status === null)
            throw new globalThis.Error("The parameter 'status' cannot be null.");
        else if (status !== undefined)
            url_ += "status=" + encodeURIComponent("" + status) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        if (cursor === null)
            throw new globalThis.Error("The parameter 'cursor' cannot be null.");
        else if (cursor !== undefined)
            url_ += "cursor=" + encodeURIComponent("" + cursor) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetIssues(_response);
        });
    }

    protected processGetIssues(response: Response): Promise<SpacePageOfSpaceIssueDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SpacePageOfSpaceIssueDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = SpaceDesignProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = SpaceDesignProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            let result403: any = null;
            let resultData403 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result403 = SpaceDesignProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = SpaceDesignProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = SpaceDesignProblemDetails.fromJS(resultData409);
            return throwException("Conflict", status, _responseText, _headers, result409);
            });
        } else if (status === 422) {
            return response.text().then((_responseText) => {
            let result422: any = null;
            let resultData422 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result422 = SpaceDesignProblemDetails.fromJS(resultData422);
            return throwException("Unprocessable Content", status, _responseText, _headers, result422);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = SpaceDesignProblemDetails.fromJS(resultData500);
            return throwException("Internal Server Error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SpacePageOfSpaceIssueDto>(null as any);
    }
}

export class CreateSpaceSourceRequest implements ICreateSpaceSourceRequest {
    fileId?: string;
    sourceType?: string | undefined;
    displayName?: string | undefined;

    constructor(data?: ICreateSpaceSourceRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.fileId = _data["fileId"];
            this.sourceType = _data["sourceType"];
            this.displayName = _data["displayName"];
        }
    }

    static fromJS(data: any): CreateSpaceSourceRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSpaceSourceRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fileId"] = this.fileId;
        data["sourceType"] = this.sourceType;
        data["displayName"] = this.displayName;
        return data;
    }
}

export interface ICreateSpaceSourceRequest {
    fileId?: string;
    sourceType?: string | undefined;
    displayName?: string | undefined;
}

export class CreateSpaceSourceResponse implements ICreateSpaceSourceResponse {
    source?: SpaceSourceDto;
    idempotentReplay?: boolean;

    constructor(data?: ICreateSpaceSourceResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.source = _data["source"] ? SpaceSourceDto.fromJS(_data["source"]) : undefined as any;
            this.idempotentReplay = _data["idempotentReplay"];
        }
    }

    static fromJS(data: any): CreateSpaceSourceResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSpaceSourceResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["source"] = this.source ? this.source.toJSON() : undefined as any;
        data["idempotentReplay"] = this.idempotentReplay;
        return data;
    }
}

export interface ICreateSpaceSourceResponse {
    source?: SpaceSourceDto;
    idempotentReplay?: boolean;
}

export class CreateSpaceVersionRequest implements ICreateSpaceVersionRequest {
    name?: string | undefined;
    basedOnVersionId?: string | undefined;
    createMode?: string | undefined;

    constructor(data?: ICreateSpaceVersionRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.basedOnVersionId = _data["basedOnVersionId"];
            this.createMode = _data["createMode"];
        }
    }

    static fromJS(data: any): CreateSpaceVersionRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSpaceVersionRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["basedOnVersionId"] = this.basedOnVersionId;
        data["createMode"] = this.createMode;
        return data;
    }
}

export interface ICreateSpaceVersionRequest {
    name?: string | undefined;
    basedOnVersionId?: string | undefined;
    createMode?: string | undefined;
}

export class CreateSpaceVersionResponse implements ICreateSpaceVersionResponse {
    id?: string;
    siteId?: string;
    versionNo?: string | undefined;
    status?: string | undefined;
    rowVersion?: string | undefined;
    jobId?: string;
    jobStatusUrl?: string | undefined;
    idempotentReplay?: boolean;

    constructor(data?: ICreateSpaceVersionResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.siteId = _data["siteId"];
            this.versionNo = _data["versionNo"];
            this.status = _data["status"];
            this.rowVersion = _data["rowVersion"];
            this.jobId = _data["jobId"];
            this.jobStatusUrl = _data["jobStatusUrl"];
            this.idempotentReplay = _data["idempotentReplay"];
        }
    }

    static fromJS(data: any): CreateSpaceVersionResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSpaceVersionResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["siteId"] = this.siteId;
        data["versionNo"] = this.versionNo;
        data["status"] = this.status;
        data["rowVersion"] = this.rowVersion;
        data["jobId"] = this.jobId;
        data["jobStatusUrl"] = this.jobStatusUrl;
        data["idempotentReplay"] = this.idempotentReplay;
        return data;
    }
}

export interface ICreateSpaceVersionResponse {
    id?: string;
    siteId?: string;
    versionNo?: string | undefined;
    status?: string | undefined;
    rowVersion?: string | undefined;
    jobId?: string;
    jobStatusUrl?: string | undefined;
    idempotentReplay?: boolean;
}

export class SpaceIssueDto implements ISpaceIssueDto {
    id?: string;
    modelVersionId?: string | undefined;
    sourceId?: string | undefined;
    jobId?: string | undefined;
    severity?: string | undefined;
    code?: string | undefined;
    sourceRef?: string | undefined;
    targetLogicalId?: string | undefined;
    messageArgsJson?: string | undefined;
    suggestedActionCode?: string | undefined;
    status?: string | undefined;
    resolutionCommandBatchId?: string | undefined;
    acknowledgedBy?: string | undefined;
    acknowledgedAtUtc?: Date | undefined;
    acknowledgementReason?: string | undefined;
    createdAtUtc?: Date;

    constructor(data?: ISpaceIssueDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modelVersionId = _data["modelVersionId"];
            this.sourceId = _data["sourceId"];
            this.jobId = _data["jobId"];
            this.severity = _data["severity"];
            this.code = _data["code"];
            this.sourceRef = _data["sourceRef"];
            this.targetLogicalId = _data["targetLogicalId"];
            this.messageArgsJson = _data["messageArgsJson"];
            this.suggestedActionCode = _data["suggestedActionCode"];
            this.status = _data["status"];
            this.resolutionCommandBatchId = _data["resolutionCommandBatchId"];
            this.acknowledgedBy = _data["acknowledgedBy"];
            this.acknowledgedAtUtc = _data["acknowledgedAtUtc"] ? new Date(_data["acknowledgedAtUtc"].toString()) : undefined as any;
            this.acknowledgementReason = _data["acknowledgementReason"];
            this.createdAtUtc = _data["createdAtUtc"] ? new Date(_data["createdAtUtc"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): SpaceIssueDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceIssueDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelVersionId"] = this.modelVersionId;
        data["sourceId"] = this.sourceId;
        data["jobId"] = this.jobId;
        data["severity"] = this.severity;
        data["code"] = this.code;
        data["sourceRef"] = this.sourceRef;
        data["targetLogicalId"] = this.targetLogicalId;
        data["messageArgsJson"] = this.messageArgsJson;
        data["suggestedActionCode"] = this.suggestedActionCode;
        data["status"] = this.status;
        data["resolutionCommandBatchId"] = this.resolutionCommandBatchId;
        data["acknowledgedBy"] = this.acknowledgedBy;
        data["acknowledgedAtUtc"] = this.acknowledgedAtUtc ? this.acknowledgedAtUtc.toISOString() : undefined as any;
        data["acknowledgementReason"] = this.acknowledgementReason;
        data["createdAtUtc"] = this.createdAtUtc ? this.createdAtUtc.toISOString() : undefined as any;
        return data;
    }
}

export interface ISpaceIssueDto {
    id?: string;
    modelVersionId?: string | undefined;
    sourceId?: string | undefined;
    jobId?: string | undefined;
    severity?: string | undefined;
    code?: string | undefined;
    sourceRef?: string | undefined;
    targetLogicalId?: string | undefined;
    messageArgsJson?: string | undefined;
    suggestedActionCode?: string | undefined;
    status?: string | undefined;
    resolutionCommandBatchId?: string | undefined;
    acknowledgedBy?: string | undefined;
    acknowledgedAtUtc?: Date | undefined;
    acknowledgementReason?: string | undefined;
    createdAtUtc?: Date;
}

export class SpaceJobDto implements ISpaceJobDto {
    id?: string;
    jobType?: string | undefined;
    subjectType?: string | undefined;
    subjectId?: string;
    status?: string | undefined;
    progressDone?: number;
    progressTotal?: number;
    progressStage?: string | undefined;
    attemptCount?: number;
    maxAttempts?: number;
    nextAttemptAtUtc?: Date | undefined;
    lockExpiresAtUtc?: Date | undefined;
    cancellationRequested?: boolean;
    lastErrorCode?: string | undefined;
    lastErrorSummary?: string | undefined;
    openInfoCount?: number;
    openWarningCount?: number;
    openBlockingCount?: number;
    requestedAtUtc?: Date;
    startedAtUtc?: Date | undefined;
    finishedAtUtc?: Date | undefined;
    resultSummaryJson?: string | undefined;
    rowVersion?: string | undefined;

    constructor(data?: ISpaceJobDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.jobType = _data["jobType"];
            this.subjectType = _data["subjectType"];
            this.subjectId = _data["subjectId"];
            this.status = _data["status"];
            this.progressDone = _data["progressDone"];
            this.progressTotal = _data["progressTotal"];
            this.progressStage = _data["progressStage"];
            this.attemptCount = _data["attemptCount"];
            this.maxAttempts = _data["maxAttempts"];
            this.nextAttemptAtUtc = _data["nextAttemptAtUtc"] ? new Date(_data["nextAttemptAtUtc"].toString()) : undefined as any;
            this.lockExpiresAtUtc = _data["lockExpiresAtUtc"] ? new Date(_data["lockExpiresAtUtc"].toString()) : undefined as any;
            this.cancellationRequested = _data["cancellationRequested"];
            this.lastErrorCode = _data["lastErrorCode"];
            this.lastErrorSummary = _data["lastErrorSummary"];
            this.openInfoCount = _data["openInfoCount"];
            this.openWarningCount = _data["openWarningCount"];
            this.openBlockingCount = _data["openBlockingCount"];
            this.requestedAtUtc = _data["requestedAtUtc"] ? new Date(_data["requestedAtUtc"].toString()) : undefined as any;
            this.startedAtUtc = _data["startedAtUtc"] ? new Date(_data["startedAtUtc"].toString()) : undefined as any;
            this.finishedAtUtc = _data["finishedAtUtc"] ? new Date(_data["finishedAtUtc"].toString()) : undefined as any;
            this.resultSummaryJson = _data["resultSummaryJson"];
            this.rowVersion = _data["rowVersion"];
        }
    }

    static fromJS(data: any): SpaceJobDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceJobDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["jobType"] = this.jobType;
        data["subjectType"] = this.subjectType;
        data["subjectId"] = this.subjectId;
        data["status"] = this.status;
        data["progressDone"] = this.progressDone;
        data["progressTotal"] = this.progressTotal;
        data["progressStage"] = this.progressStage;
        data["attemptCount"] = this.attemptCount;
        data["maxAttempts"] = this.maxAttempts;
        data["nextAttemptAtUtc"] = this.nextAttemptAtUtc ? this.nextAttemptAtUtc.toISOString() : undefined as any;
        data["lockExpiresAtUtc"] = this.lockExpiresAtUtc ? this.lockExpiresAtUtc.toISOString() : undefined as any;
        data["cancellationRequested"] = this.cancellationRequested;
        data["lastErrorCode"] = this.lastErrorCode;
        data["lastErrorSummary"] = this.lastErrorSummary;
        data["openInfoCount"] = this.openInfoCount;
        data["openWarningCount"] = this.openWarningCount;
        data["openBlockingCount"] = this.openBlockingCount;
        data["requestedAtUtc"] = this.requestedAtUtc ? this.requestedAtUtc.toISOString() : undefined as any;
        data["startedAtUtc"] = this.startedAtUtc ? this.startedAtUtc.toISOString() : undefined as any;
        data["finishedAtUtc"] = this.finishedAtUtc ? this.finishedAtUtc.toISOString() : undefined as any;
        data["resultSummaryJson"] = this.resultSummaryJson;
        data["rowVersion"] = this.rowVersion;
        return data;
    }
}

export interface ISpaceJobDto {
    id?: string;
    jobType?: string | undefined;
    subjectType?: string | undefined;
    subjectId?: string;
    status?: string | undefined;
    progressDone?: number;
    progressTotal?: number;
    progressStage?: string | undefined;
    attemptCount?: number;
    maxAttempts?: number;
    nextAttemptAtUtc?: Date | undefined;
    lockExpiresAtUtc?: Date | undefined;
    cancellationRequested?: boolean;
    lastErrorCode?: string | undefined;
    lastErrorSummary?: string | undefined;
    openInfoCount?: number;
    openWarningCount?: number;
    openBlockingCount?: number;
    requestedAtUtc?: Date;
    startedAtUtc?: Date | undefined;
    finishedAtUtc?: Date | undefined;
    resultSummaryJson?: string | undefined;
    rowVersion?: string | undefined;
}

export class SpaceModelDto implements ISpaceModelDto {
    id?: string;
    siteId?: string;
    mode?: string | undefined;
    cutoverState?: string | undefined;
    activeDraftVersionId?: string | undefined;
    currentPublishedVersionId?: string | undefined;
    rowVersion?: string | undefined;

    constructor(data?: ISpaceModelDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.siteId = _data["siteId"];
            this.mode = _data["mode"];
            this.cutoverState = _data["cutoverState"];
            this.activeDraftVersionId = _data["activeDraftVersionId"];
            this.currentPublishedVersionId = _data["currentPublishedVersionId"];
            this.rowVersion = _data["rowVersion"];
        }
    }

    static fromJS(data: any): SpaceModelDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceModelDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["siteId"] = this.siteId;
        data["mode"] = this.mode;
        data["cutoverState"] = this.cutoverState;
        data["activeDraftVersionId"] = this.activeDraftVersionId;
        data["currentPublishedVersionId"] = this.currentPublishedVersionId;
        data["rowVersion"] = this.rowVersion;
        return data;
    }
}

export interface ISpaceModelDto {
    id?: string;
    siteId?: string;
    mode?: string | undefined;
    cutoverState?: string | undefined;
    activeDraftVersionId?: string | undefined;
    currentPublishedVersionId?: string | undefined;
    rowVersion?: string | undefined;
}

export class SpaceSourceDto implements ISpaceSourceDto {
    id?: string;
    modelVersionId?: string;
    sourceType?: string | undefined;
    fileId?: string | undefined;
    displayName?: string | undefined;
    sha256?: string | undefined;
    state?: string | undefined;
    parserVersion?: string | undefined;
    mappingProfileId?: string | undefined;
    mappingProfileVersion?: number | undefined;
    unit?: string | undefined;
    scaleToMillimeters?: number | undefined;
    rowVersion?: string | undefined;

    constructor(data?: ISpaceSourceDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modelVersionId = _data["modelVersionId"];
            this.sourceType = _data["sourceType"];
            this.fileId = _data["fileId"];
            this.displayName = _data["displayName"];
            this.sha256 = _data["sha256"];
            this.state = _data["state"];
            this.parserVersion = _data["parserVersion"];
            this.mappingProfileId = _data["mappingProfileId"];
            this.mappingProfileVersion = _data["mappingProfileVersion"];
            this.unit = _data["unit"];
            this.scaleToMillimeters = _data["scaleToMillimeters"];
            this.rowVersion = _data["rowVersion"];
        }
    }

    static fromJS(data: any): SpaceSourceDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceSourceDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelVersionId"] = this.modelVersionId;
        data["sourceType"] = this.sourceType;
        data["fileId"] = this.fileId;
        data["displayName"] = this.displayName;
        data["sha256"] = this.sha256;
        data["state"] = this.state;
        data["parserVersion"] = this.parserVersion;
        data["mappingProfileId"] = this.mappingProfileId;
        data["mappingProfileVersion"] = this.mappingProfileVersion;
        data["unit"] = this.unit;
        data["scaleToMillimeters"] = this.scaleToMillimeters;
        data["rowVersion"] = this.rowVersion;
        return data;
    }
}

export interface ISpaceSourceDto {
    id?: string;
    modelVersionId?: string;
    sourceType?: string | undefined;
    fileId?: string | undefined;
    displayName?: string | undefined;
    sha256?: string | undefined;
    state?: string | undefined;
    parserVersion?: string | undefined;
    mappingProfileId?: string | undefined;
    mappingProfileVersion?: number | undefined;
    unit?: string | undefined;
    scaleToMillimeters?: number | undefined;
    rowVersion?: string | undefined;
}

export class SpaceVersionDto implements ISpaceVersionDto {
    id?: string;
    modelId?: string;
    siteId?: string;
    versionNo?: string | undefined;
    name?: string | undefined;
    status?: string | undefined;
    basedOnVersionId?: string | undefined;
    contentRevision?: number;
    contentHash?: string | undefined;
    validatedHash?: string | undefined;
    publishedAtUtc?: Date | undefined;
    rowVersion?: string | undefined;

    constructor(data?: ISpaceVersionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.modelId = _data["modelId"];
            this.siteId = _data["siteId"];
            this.versionNo = _data["versionNo"];
            this.name = _data["name"];
            this.status = _data["status"];
            this.basedOnVersionId = _data["basedOnVersionId"];
            this.contentRevision = _data["contentRevision"];
            this.contentHash = _data["contentHash"];
            this.validatedHash = _data["validatedHash"];
            this.publishedAtUtc = _data["publishedAtUtc"] ? new Date(_data["publishedAtUtc"].toString()) : undefined as any;
            this.rowVersion = _data["rowVersion"];
        }
    }

    static fromJS(data: any): SpaceVersionDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceVersionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["modelId"] = this.modelId;
        data["siteId"] = this.siteId;
        data["versionNo"] = this.versionNo;
        data["name"] = this.name;
        data["status"] = this.status;
        data["basedOnVersionId"] = this.basedOnVersionId;
        data["contentRevision"] = this.contentRevision;
        data["contentHash"] = this.contentHash;
        data["validatedHash"] = this.validatedHash;
        data["publishedAtUtc"] = this.publishedAtUtc ? this.publishedAtUtc.toISOString() : undefined as any;
        data["rowVersion"] = this.rowVersion;
        return data;
    }
}

export interface ISpaceVersionDto {
    id?: string;
    modelId?: string;
    siteId?: string;
    versionNo?: string | undefined;
    name?: string | undefined;
    status?: string | undefined;
    basedOnVersionId?: string | undefined;
    contentRevision?: number;
    contentHash?: string | undefined;
    validatedHash?: string | undefined;
    publishedAtUtc?: Date | undefined;
    rowVersion?: string | undefined;
}

export class SpaceDesignProblemDetails implements ISpaceDesignProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    code!: string;
    traceId!: string;
    correlationId!: string;
    recovery!: SpaceRecoveryDetails;

    [key: string]: any;

    constructor(data?: ISpaceDesignProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.recovery = new SpaceRecoveryDetails();
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
            this.code = _data["code"];
            this.traceId = _data["traceId"];
            this.correlationId = _data["correlationId"];
            this.recovery = _data["recovery"] ? SpaceRecoveryDetails.fromJS(_data["recovery"]) : new SpaceRecoveryDetails();
        }
    }

    static fromJS(data: any): SpaceDesignProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceDesignProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        data["code"] = this.code;
        data["traceId"] = this.traceId;
        data["correlationId"] = this.correlationId;
        data["recovery"] = this.recovery ? this.recovery.toJSON() : undefined as any;
        return data;
    }
}

export interface ISpaceDesignProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    code: string;
    traceId: string;
    correlationId: string;
    recovery: SpaceRecoveryDetails;

    [key: string]: any;
}

export class SpaceRecoveryDetails implements ISpaceRecoveryDetails {
    action!: string;
    retryable?: boolean;

    constructor(data?: ISpaceRecoveryDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.action = _data["action"];
            this.retryable = _data["retryable"];
        }
    }

    static fromJS(data: any): SpaceRecoveryDetails {
        data = typeof data === 'object' ? data : {};
        let result = new SpaceRecoveryDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["action"] = this.action;
        data["retryable"] = this.retryable;
        return data;
    }
}

export interface ISpaceRecoveryDetails {
    action: string;
    retryable?: boolean;
}

export class SpacePageOfSpaceIssueDto implements ISpacePageOfSpaceIssueDto {
    items?: SpaceIssueDto[] | undefined;
    nextCursor?: string | undefined;

    constructor(data?: ISpacePageOfSpaceIssueDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(SpaceIssueDto.fromJS(item));
            }
            this.nextCursor = _data["nextCursor"];
        }
    }

    static fromJS(data: any): SpacePageOfSpaceIssueDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpacePageOfSpaceIssueDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["nextCursor"] = this.nextCursor;
        return data;
    }
}

export interface ISpacePageOfSpaceIssueDto {
    items?: SpaceIssueDto[] | undefined;
    nextCursor?: string | undefined;
}

export class SpacePageOfSpaceSourceDto implements ISpacePageOfSpaceSourceDto {
    items?: SpaceSourceDto[] | undefined;
    nextCursor?: string | undefined;

    constructor(data?: ISpacePageOfSpaceSourceDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(SpaceSourceDto.fromJS(item));
            }
            this.nextCursor = _data["nextCursor"];
        }
    }

    static fromJS(data: any): SpacePageOfSpaceSourceDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpacePageOfSpaceSourceDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["nextCursor"] = this.nextCursor;
        return data;
    }
}

export interface ISpacePageOfSpaceSourceDto {
    items?: SpaceSourceDto[] | undefined;
    nextCursor?: string | undefined;
}

export class SpacePageOfSpaceVersionDto implements ISpacePageOfSpaceVersionDto {
    items?: SpaceVersionDto[] | undefined;
    nextCursor?: string | undefined;

    constructor(data?: ISpacePageOfSpaceVersionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(SpaceVersionDto.fromJS(item));
            }
            this.nextCursor = _data["nextCursor"];
        }
    }

    static fromJS(data: any): SpacePageOfSpaceVersionDto {
        data = typeof data === 'object' ? data : {};
        let result = new SpacePageOfSpaceVersionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["nextCursor"] = this.nextCursor;
        return data;
    }
}

export interface ISpacePageOfSpaceVersionDto {
    items?: SpaceVersionDto[] | undefined;
    nextCursor?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}
