<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CP6.Space.CadExperiment\CP6.Space.CadExperiment.csproj" />
    <PackageReference Include="Aspose.CAD" Version="26.6.0" />
  </ItemGroup>
</Project>
