SET NOCOUNT ON;
SET LOCK_TIMEOUT 5000;
SELECT t.name AS table_name,
 JSON_QUERY((SELECT c.name AS column_name, ty.name AS sql_type, c.max_length, c.precision, c.scale, c.is_nullable, c.is_identity, c.is_computed, c.generated_always_type, dc.definition AS default_sql, cc.definition AS computed_sql FROM sys.columns c JOIN sys.types ty ON c.user_type_id=ty.user_type_id LEFT JOIN sys.default_constraints dc ON c.default_object_id=dc.object_id LEFT JOIN sys.computed_columns cc ON c.object_id=cc.object_id AND c.column_id=cc.column_id WHERE c.object_id=t.object_id ORDER BY c.column_id FOR JSON PATH, INCLUDE_NULL_VALUES)) AS columns,
 JSON_QUERY((SELECT i.name, i.type_desc, i.is_unique, i.is_primary_key, i.is_unique_constraint, i.is_disabled, i.is_hypothetical, i.filter_definition,
 JSON_QUERY((SELECT c.name AS column_name, ic.key_ordinal, ic.is_descending_key, ic.is_included_column FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id ORDER BY ic.index_column_id FOR JSON PATH)) AS columns FROM sys.indexes i WHERE i.object_id=t.object_id ORDER BY i.name FOR JSON PATH, INCLUDE_NULL_VALUES)) AS indexes,
 JSON_QUERY((SELECT fk.name, rs.name AS target_schema, rt.name AS target_table, fk.delete_referential_action_desc, fk.update_referential_action_desc, fk.is_disabled, fk.is_not_trusted, fk.is_not_for_replication,
 JSON_QUERY((SELECT pc.name AS column_name, rc.name AS target_column FROM sys.foreign_key_columns fc JOIN sys.columns pc ON pc.object_id=fc.parent_object_id AND pc.column_id=fc.parent_column_id JOIN sys.columns rc ON rc.object_id=fc.referenced_object_id AND rc.column_id=fc.referenced_column_id WHERE fc.constraint_object_id=fk.object_id ORDER BY fc.constraint_column_id FOR JSON PATH)) AS columns FROM sys.foreign_keys fk JOIN sys.tables rt ON fk.referenced_object_id=rt.object_id JOIN sys.schemas rs ON rt.schema_id=rs.schema_id WHERE fk.parent_object_id=t.object_id ORDER BY fk.name FOR JSON PATH)) AS foreign_keys,
 JSON_QUERY((SELECT name, is_disabled, is_not_trusted, definition FROM sys.check_constraints WHERE parent_object_id=t.object_id ORDER BY name FOR JSON PATH)) AS checks,
 (SELECT COUNT_BIG(*) FROM sys.triggers tr WHERE tr.parent_id=t.object_id) AS trigger_count
FROM sys.tables t JOIN sys.schemas s ON t.schema_id=s.schema_id WHERE s.name=N'dbo' AND t.name LIKE N'Crm[_]%' ORDER BY t.name FOR JSON PATH;