// <auto-generated />
using System;
using CP6.Space.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP6.Space.Infrastructure.Migrations
{
    [DbContext(typeof(SpaceContext))]
    [Migration("20260726092519_SpaceE01S05DesignApiIdempotency")]
    partial class SpaceE01S05DesignApiIdempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP6.Space.Domain.SpaceAisleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AisleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CenterlineJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Direction")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "ZoneLogicalId", "AisleCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_AisleRevision_Zone_Code_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_AisleRevision", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("ArtifactType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Artifact_TenantId_Id");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_File_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "JobId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Job_Active")
                        .HasFilter("[JobId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Version");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Version_Source_Active")
                        .HasFilter("[SourceId] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Space_Artifact", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceElementAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ElementRevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ModelVersionId", "ElementRevisionId", "Namespace", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ElementAttribute_Element_Key_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_ElementAttribute", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceElementRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FloorLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LinkedLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModelAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RotationZ")
                        .HasColumnType("decimal(9,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ModelVersionId", "ParentLogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "FloorLogicalId", "ElementType")
                        .HasDatabaseName("IX_Space_ElementRevision_Floor_Type");

                    b.ToTable("Space_ElementRevision", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_ElementRevision_Geometry", "[RotationZ] >= 0 AND [RotationZ] < 360 AND [Width] >= 0 AND [Height] >= 0 AND [Depth] >= 0");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeclaredContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<short>("RetentionClass")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScanEngine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScanResultCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("SignatureVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_File_TenantId_Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_File_StorageKey");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("IX_Space_File_Tenant_State");

                    b.HasIndex("TenantId", "Sha256", "RetentionClass")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_File_Tenant_Hash_Retention_Reusable")
                        .HasFilter("[Sha256] IS NOT NULL AND [State] IN (1, 2, 3) AND [IsDeleted] = 0");

                    b.ToTable("Space_File", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceFloorRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoundaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Elevation")
                        .HasColumnType("int");

                    b.Property<string>("FloorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SiteLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnderlayOffsetX")
                        .HasColumnType("int");

                    b.Property<int>("UnderlayOffsetY")
                        .HasColumnType("int");

                    b.Property<decimal>("UnderlayRotationZ")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("UnderlayScale")
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("UnderlaySourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasIndex("TenantId", "ModelVersionId", "FloorCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_FloorRevision_Version_Code_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId", "Level")
                        .HasDatabaseName("IX_Space_FloorRevision_Version_Level");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "UnderlaySourceId");

                    b.ToTable("Space_FloorRevision", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReplayUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RetainUntilUtc")
                        .HasDatabaseName("IX_Space_IdempotencyRecord_Tenant_Retention");

                    b.HasIndex("TenantId", "PrincipalId", "Operation", "IdempotencyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_IdempotencyRecord_Tenant_Principal_Operation_Key")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_IdempotencyRecord", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancellationRequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("JobType")
                        .HasColumnType("smallint");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("LastFailureKind")
                        .HasColumnType("smallint");

                    b.Property<long>("LeaseRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LockExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<long>("ProgressDone")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProgressTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RetryOfJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SubjectType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Job_TenantId_Id");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_Space_Job_Tenant_Correlation");

                    b.HasIndex("TenantId", "RetryOfJobId");

                    b.HasIndex("TenantId", "JobType", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Job_Tenant_Type_BusinessKey_Active")
                        .HasFilter("[Status] IN (0, 1) AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId")
                        .HasDatabaseName("IX_Space_Job_Tenant_Subject");

                    b.HasIndex("TenantId", "Status", "NextAttemptAtUtc", "LockExpiresAtUtc", "Priority", "RequestedAtUtc")
                        .HasDatabaseName("IX_Space_Job_Tenant_Claim");

                    b.ToTable("Space_Job", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_Job_Attempts", "[AttemptCount] >= 0 AND [MaxAttempts] BETWEEN 1 AND 20 AND [AttemptCount] <= [MaxAttempts]");

                            t.HasCheckConstraint("CK_Space_Job_Lease", "([Status] = 1 AND [LockedBy] IS NOT NULL AND [LockedAtUtc] IS NOT NULL AND [LockExpiresAtUtc] IS NOT NULL AND [ActiveAttemptId] IS NOT NULL) OR ([Status] <> 1 AND [LockedBy] IS NULL AND [LockedAtUtc] IS NULL AND [LockExpiresAtUtc] IS NULL AND [ActiveAttemptId] IS NULL)");

                            t.HasCheckConstraint("CK_Space_Job_Progress", "[ProgressDone] >= 0 AND [ProgressTotal] >= 0 AND ([ProgressTotal] = 0 OR [ProgressDone] <= [ProgressTotal])");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DiagnosticArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("FailureKind")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint");

                    b.Property<string>("ProcessorVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceUsageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_JobAttempt_TenantId_Id");

                    b.HasIndex("TenantId", "DiagnosticArtifactId");

                    b.HasIndex("TenantId", "JobId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobAttempt_Tenant_Job_AttemptNo");

                    b.HasIndex("TenantId", "JobId", "StartedAtUtc")
                        .HasDatabaseName("IX_Space_JobAttempt_Tenant_Job_Started");

                    b.ToTable("Space_JobAttempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_JobAttempt_OutcomeTime", "([Outcome] = 0 AND [FinishedAtUtc] IS NULL) OR ([Outcome] <> 0 AND [FinishedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckpointJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AttemptId", "StepCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobStep_Tenant_Attempt_StepCode");

                    b.HasIndex("TenantId", "AttemptId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobStep_Tenant_Attempt_StepNo");

                    b.ToTable("Space_JobStep", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_JobStep_StatusTime", "([Status] = 0 AND [FinishedAtUtc] IS NULL) OR ([Status] <> 0 AND [FinishedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceLocationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CodeOrigin")
                        .HasColumnType("smallint");

                    b.Property<int>("ColumnNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("DepthNo")
                        .HasColumnType("int");

                    b.Property<short>("ExternalBindingState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("FloorLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LevelNo")
                        .HasColumnType("int");

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<string>("LocationCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxLoad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RackLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "LogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "FloorLogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "LocationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_LocationRevision_Version_Code_Active")
                        .HasFilter("[LocationCode] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "RackLogicalId", "LevelNo", "ColumnNo", "DepthNo")
                        .HasDatabaseName("IX_Space_LocationRevision_Rack_Position_Active")
                        .HasFilter("[RackLogicalId] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Space_LocationRevision", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_LocationRevision_Dimensions", "[ColumnNo] > 0 AND [LevelNo] > 0 AND [DepthNo] > 0 AND [Width] > 0 AND [Height] > 0 AND [Depth] > 0 AND ([MaxLoad] IS NULL OR [MaxLoad] >= 0)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveDraftVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CutoverOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CutoverState")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastMaterializedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<short>("Mode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Model_TenantId_Id");

                    b.HasIndex("TenantId", "ActiveDraftVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_ActiveDraft")
                        .HasFilter("[ActiveDraftVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "CurrentPublishedVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_CurrentPublished")
                        .HasFilter("[CurrentPublishedVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_Site_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "Id", "ActiveDraftVersionId");

                    b.HasIndex("TenantId", "Id", "CurrentPublishedVersionId");

                    b.ToTable("Space_Model", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcknowledgementReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageArgsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolutionCommandBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("SuggestedActionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TargetLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "JobId", "Status")
                        .HasDatabaseName("IX_Space_ModelIssue_Tenant_Job_Status")
                        .HasFilter("[JobId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "Status", "Severity", "Code")
                        .HasDatabaseName("IX_Space_ModelIssue_Tenant_Version_Status");

                    b.ToTable("Space_ModelIssue", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_ModelIssue_Context", "[ModelVersionId] IS NOT NULL OR [SourceId] IS NOT NULL OR [JobId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Space_ModelIssue_SourceVersion", "[SourceId] IS NULL OR [ModelVersionId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImportedCommandBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MappingProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("MappingProfileVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParserVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("ScaleToMillimeters")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransformJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id")
                        .HasName("AK_Space_ModelSource_TenantId_ModelVersionId_Id");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_Space_ModelSource_Tenant_File_Active")
                        .HasFilter("[FileId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("IX_Space_ModelSource_Tenant_SourceHash");

                    b.HasIndex("TenantId", "ModelVersionId", "Sha256", "SourceType")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelSource_Version_Hash_Type_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_ModelSource", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasedOnVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CloneOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("ContentRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RuleSetVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidatedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("VersionNo")
                        .HasColumnType("bigint");

                    b.Property<string>("WmsCapabilityHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_ModelVersion_TenantId_Id");

                    b.HasAlternateKey("TenantId", "ModelId", "Id")
                        .HasName("AK_Space_ModelVersion_TenantId_ModelId_Id");

                    b.HasIndex("TenantId", "BasedOnVersionId")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_BasedOn")
                        .HasFilter("[BasedOnVersionId] IS NOT NULL");

                    b.HasIndex("TenantId", "ModelId", "BasedOnVersionId");

                    b.HasIndex("TenantId", "ModelId", "CloneOperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelVersion_Tenant_Model_CloneOperation")
                        .HasFilter("[CloneOperationId] IS NOT NULL");

                    b.HasIndex("TenantId", "ModelId", "Status")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_Model_Status");

                    b.HasIndex("TenantId", "ModelId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelVersion_Tenant_Model_VersionNo");

                    b.ToTable("Space_ModelVersion", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceRackLevelRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BinCount")
                        .HasColumnType("int");

                    b.Property<int>("BottomZ")
                        .HasColumnType("int");

                    b.Property<int>("CellDepth")
                        .HasColumnType("int");

                    b.Property<int>("CellWidth")
                        .HasColumnType("int");

                    b.Property<int>("ClearHeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DepthCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LevelNo")
                        .HasColumnType("int");

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxLoad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RackLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "LogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "RackLogicalId", "LevelNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_RackLevelRevision_Rack_Level_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_RackLevelRevision", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_RackLevelRevision_Dimensions", "[LevelNo] > 0 AND [ClearHeight] > 0 AND [BinCount] > 0 AND [DepthCount] > 0 AND [CellWidth] > 0 AND [CellDepth] > 0 AND ([MaxLoad] IS NULL OR [MaxLoad] >= 0)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceRackRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AisleLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<Guid>("FloorLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RackCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RotationZ")
                        .HasColumnType("decimal(9,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.Property<Guid>("ZoneLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasIndex("TenantId", "ModelVersionId", "AisleLogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "FloorLogicalId");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "ZoneLogicalId", "RackCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_RackRevision_Zone_Code_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_RackRevision", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_RackRevision_Geometry", "[RotationZ] >= 0 AND [RotationZ] < 360 AND [Width] >= 0 AND [Depth] >= 0 AND [Height] >= 0");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceZoneRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityFlags")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FloorLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("LogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("ZoneType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "FloorLogicalId", "ZoneCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ZoneRevision_Floor_Code_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_ZoneRevision", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceAisleRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CP6.Space.Domain.SpaceZoneRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "ZoneLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_AisleRevision_Zone_Tenant_Version_Logical");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceArtifact", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceFile", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FileId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_Artifact_File_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Artifact_Job_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_Artifact_Version_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Artifact_Source_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceElementAttribute", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceElementRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "ElementRevisionId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ElementAttribute_Element_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceElementRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceFloorRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "FloorLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ElementRevision_Floor_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceElementRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "ParentLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ElementRevision_Parent_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceFloorRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "UnderlaySourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_FloorRevision_UnderlaySource_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJob", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RetryOfJobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Job_RetryOf_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobAttempt", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceArtifact", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DiagnosticArtifactId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_JobAttempt_DiagnosticArtifact_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_JobAttempt_Job_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobStep", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJobAttempt", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AttemptId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_JobStep_Attempt_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceLocationRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceFloorRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "FloorLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_LocationRevision_Floor_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceRackRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "RackLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_LocationRevision_Rack_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "ActiveDraftVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_ActiveDraft_Tenant_Model_Version");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "CurrentPublishedVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_CurrentPublished_Tenant_Model_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelIssue", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Job_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Version_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Source_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelSource", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceFile", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FileId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelSource_File_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ModelSource_Version_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModel", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ModelVersion_Space_Model_Tenant_Model");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId", "BasedOnVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelVersion_BasedOn_Tenant_Model_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceRackLevelRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceRackRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "RackLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_RackLevelRevision_Rack_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceRackRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceAisleRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "AisleLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_RackRevision_Aisle_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceFloorRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "FloorLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_RackRevision_Floor_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CP6.Space.Domain.SpaceZoneRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "ZoneLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_RackRevision_Zone_Tenant_Version_Logical");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceZoneRevision", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Space.Domain.SpaceFloorRevision", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "FloorLogicalId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "LogicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ZoneRevision_Floor_Tenant_Version_Logical");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
