// <auto-generated />
using System;
using CP6.Space.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP6.Space.Infrastructure.Migrations
{
    [DbContext(typeof(SpaceContext))]
    [Migration("20260726080918_SpaceE01S03JobLedger")]
    partial class SpaceE01S03JobLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP6.Space.Domain.SpaceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("ArtifactType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Artifact_TenantId_Id");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_File_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "JobId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Job_Active")
                        .HasFilter("[JobId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Version");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId")
                        .HasDatabaseName("IX_Space_Artifact_Tenant_Version_Source_Active")
                        .HasFilter("[SourceId] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Space_Artifact", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeclaredContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<short>("RetentionClass")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScanEngine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScanResultCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("SignatureVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_File_TenantId_Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_File_StorageKey");

                    b.HasIndex("TenantId", "State")
                        .HasDatabaseName("IX_Space_File_Tenant_State");

                    b.HasIndex("TenantId", "Sha256", "RetentionClass")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_File_Tenant_Hash_Retention_Reusable")
                        .HasFilter("[Sha256] IS NOT NULL AND [State] IN (1, 2, 3) AND [IsDeleted] = 0");

                    b.ToTable("Space_File", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancellationRequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("JobType")
                        .HasColumnType("smallint");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("LastFailureKind")
                        .HasColumnType("smallint");

                    b.Property<long>("LeaseRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LockExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<long>("ProgressDone")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressStage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProgressTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RetryOfJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("SubjectType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Job_TenantId_Id");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_Space_Job_Tenant_Correlation");

                    b.HasIndex("TenantId", "RetryOfJobId");

                    b.HasIndex("TenantId", "JobType", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Job_Tenant_Type_BusinessKey_Active")
                        .HasFilter("[Status] IN (0, 1) AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId")
                        .HasDatabaseName("IX_Space_Job_Tenant_Subject");

                    b.HasIndex("TenantId", "Status", "NextAttemptAtUtc", "LockExpiresAtUtc", "Priority", "RequestedAtUtc")
                        .HasDatabaseName("IX_Space_Job_Tenant_Claim");

                    b.ToTable("Space_Job", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_Job_Attempts", "[AttemptCount] >= 0 AND [MaxAttempts] BETWEEN 1 AND 20 AND [AttemptCount] <= [MaxAttempts]");

                            t.HasCheckConstraint("CK_Space_Job_Lease", "([Status] = 1 AND [LockedBy] IS NOT NULL AND [LockedAtUtc] IS NOT NULL AND [LockExpiresAtUtc] IS NOT NULL AND [ActiveAttemptId] IS NOT NULL) OR ([Status] <> 1 AND [LockedBy] IS NULL AND [LockedAtUtc] IS NULL AND [LockExpiresAtUtc] IS NULL AND [ActiveAttemptId] IS NULL)");

                            t.HasCheckConstraint("CK_Space_Job_Progress", "[ProgressDone] >= 0 AND [ProgressTotal] >= 0 AND ([ProgressTotal] = 0 OR [ProgressDone] <= [ProgressTotal])");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DiagnosticArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("FailureKind")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint");

                    b.Property<string>("ProcessorVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceUsageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_JobAttempt_TenantId_Id");

                    b.HasIndex("TenantId", "DiagnosticArtifactId");

                    b.HasIndex("TenantId", "JobId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobAttempt_Tenant_Job_AttemptNo");

                    b.HasIndex("TenantId", "JobId", "StartedAtUtc")
                        .HasDatabaseName("IX_Space_JobAttempt_Tenant_Job_Started");

                    b.ToTable("Space_JobAttempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_JobAttempt_OutcomeTime", "([Outcome] = 0 AND [FinishedAtUtc] IS NULL) OR ([Outcome] <> 0 AND [FinishedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckpointJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StepCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AttemptId", "StepCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobStep_Tenant_Attempt_StepCode");

                    b.HasIndex("TenantId", "AttemptId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_JobStep_Tenant_Attempt_StepNo");

                    b.ToTable("Space_JobStep", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_JobStep_StatusTime", "([Status] = 0 AND [FinishedAtUtc] IS NULL) OR ([Status] <> 0 AND [FinishedAtUtc] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveDraftVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CutoverOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CutoverState")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastMaterializedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<short>("Mode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Model_TenantId_Id");

                    b.HasIndex("TenantId", "ActiveDraftVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_ActiveDraft")
                        .HasFilter("[ActiveDraftVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "CurrentPublishedVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_CurrentPublished")
                        .HasFilter("[CurrentPublishedVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_Site_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "Id", "ActiveDraftVersionId");

                    b.HasIndex("TenantId", "Id", "CurrentPublishedVersionId");

                    b.ToTable("Space_Model", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcknowledgementReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageArgsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolutionCommandBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("SuggestedActionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TargetLogicalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "JobId", "Status")
                        .HasDatabaseName("IX_Space_ModelIssue_Tenant_Job_Status")
                        .HasFilter("[JobId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "ModelVersionId", "SourceId");

                    b.HasIndex("TenantId", "ModelVersionId", "Status", "Severity", "Code")
                        .HasDatabaseName("IX_Space_ModelIssue_Tenant_Version_Status");

                    b.ToTable("Space_ModelIssue", null, t =>
                        {
                            t.HasCheckConstraint("CK_Space_ModelIssue_Context", "[ModelVersionId] IS NOT NULL OR [SourceId] IS NOT NULL OR [JobId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Space_ModelIssue_SourceVersion", "[SourceId] IS NULL OR [ModelVersionId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImportedCommandBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MappingProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("MappingProfileVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParserVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("ScaleToMillimeters")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransformJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelVersionId", "Id")
                        .HasName("AK_Space_ModelSource_TenantId_ModelVersionId_Id");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_Space_ModelSource_Tenant_File_Active")
                        .HasFilter("[FileId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("IX_Space_ModelSource_Tenant_SourceHash");

                    b.HasIndex("TenantId", "ModelVersionId", "Sha256", "SourceType")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelSource_Version_Hash_Type_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Space_ModelSource", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasedOnVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("ContentRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RuleSetVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidatedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("VersionNo")
                        .HasColumnType("bigint");

                    b.Property<string>("WmsCapabilityHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_ModelVersion_TenantId_Id");

                    b.HasAlternateKey("TenantId", "ModelId", "Id")
                        .HasName("AK_Space_ModelVersion_TenantId_ModelId_Id");

                    b.HasIndex("TenantId", "BasedOnVersionId")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_BasedOn")
                        .HasFilter("[BasedOnVersionId] IS NOT NULL");

                    b.HasIndex("TenantId", "ModelId", "BasedOnVersionId");

                    b.HasIndex("TenantId", "ModelId", "Status")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_Model_Status");

                    b.HasIndex("TenantId", "ModelId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelVersion_Tenant_Model_VersionNo");

                    b.ToTable("Space_ModelVersion", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceArtifact", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceFile", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FileId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_Artifact_File_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Artifact_Job_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_Artifact_Version_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Artifact_Source_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJob", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RetryOfJobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Job_RetryOf_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobAttempt", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceArtifact", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DiagnosticArtifactId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_JobAttempt_DiagnosticArtifact_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_JobAttempt_Job_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceJobStep", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJobAttempt", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AttemptId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_JobStep_Attempt_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "ActiveDraftVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_ActiveDraft_Tenant_Model_Version");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "CurrentPublishedVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_CurrentPublished_Tenant_Model_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelIssue", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceJob", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "JobId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Job_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Version_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelSource", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId", "SourceId")
                        .HasPrincipalKey("TenantId", "ModelVersionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelIssue_Source_Tenant_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelSource", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceFile", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "FileId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelSource_File_Tenant");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ModelSource_Version_Tenant");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModel", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ModelVersion_Space_Model_Tenant_Model");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId", "BasedOnVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelVersion_BasedOn_Tenant_Model_Version");
                });
#pragma warning restore 612, 618
        }
    }
}
