// <auto-generated />
using System;
using CP6.Space.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP6.Space.Infrastructure.Migrations
{
    [DbContext(typeof(SpaceContext))]
    partial class SpaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveDraftVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CutoverOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("CutoverState")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastMaterializedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<short>("Mode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("AK_Space_Model_TenantId_Id");

                    b.HasIndex("TenantId", "ActiveDraftVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_ActiveDraft")
                        .HasFilter("[ActiveDraftVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "CurrentPublishedVersionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_CurrentPublished")
                        .HasFilter("[CurrentPublishedVersionId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("TenantId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_Model_Tenant_Site_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId", "Id", "ActiveDraftVersionId");

                    b.HasIndex("TenantId", "Id", "CurrentPublishedVersionId");

                    b.ToTable("Space_Model", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasedOnVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("ContentRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RuleSetVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValidatedHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("VersionNo")
                        .HasColumnType("bigint");

                    b.Property<string>("WmsCapabilityHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ModelId", "Id")
                        .HasName("AK_Space_ModelVersion_TenantId_ModelId_Id");

                    b.HasIndex("TenantId", "BasedOnVersionId")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_BasedOn")
                        .HasFilter("[BasedOnVersionId] IS NOT NULL");

                    b.HasIndex("TenantId", "ModelId", "BasedOnVersionId");

                    b.HasIndex("TenantId", "ModelId", "Status")
                        .HasDatabaseName("IX_Space_ModelVersion_Tenant_Model_Status");

                    b.HasIndex("TenantId", "ModelId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Space_ModelVersion_Tenant_Model_VersionNo");

                    b.ToTable("Space_ModelVersion", (string)null);
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModel", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "ActiveDraftVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_ActiveDraft_Tenant_Model_Version");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "Id", "CurrentPublishedVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_Model_CurrentPublished_Tenant_Model_Version");
                });

            modelBuilder.Entity("CP6.Space.Domain.SpaceModelVersion", b =>
                {
                    b.HasOne("CP6.Space.Domain.SpaceModel", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Space_ModelVersion_Space_Model_Tenant_Model");

                    b.HasOne("CP6.Space.Domain.SpaceModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ModelId", "BasedOnVersionId")
                        .HasPrincipalKey("TenantId", "ModelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Space_ModelVersion_BasedOn_Tenant_Model_Version");
                });
#pragma warning restore 612, 618
        }
    }
}
