namespace CP6.Space.Contracts;

public sealed record SpaceDeviceCurrentPageDto(
    Guid SiteId,
    Guid PublishedVersionId,
    DateTimeOffset AsOfUtc,
    int FreshnessThresholdSeconds,
    IReadOnlyList<SpaceDeviceCurrentDto> Items,
    string? NextCursor);

public sealed record SpaceDeviceCurrentDto(
    Guid MappingId,
    string SourceId,
    string SourceKind,
    string DeviceExternalId,
    string DeviceKind,
    Guid ElementLogicalId,
    string ElementType,
    bool MappingIsCurrent,
    Guid? MappedFloorLogicalId,
    decimal? MappedXMillimeters,
    decimal? MappedYMillimeters,
    decimal? MappedZMillimeters,
    string OperatingState,
    Guid? FloorLogicalId,
    Guid? LocationLogicalId,
    decimal? XMillimeters,
    decimal? YMillimeters,
    decimal? ZMillimeters,
    decimal? AccuracyMillimeters,
    DateTimeOffset? PositionOccurredAtUtc,
    DateTimeOffset? PositionReceivedAtUtc,
    Guid? PositionEventId,
    string? PositionSourceEventId,
    DateTimeOffset? OperatingStateOccurredAtUtc,
    DateTimeOffset? OperatingStateReceivedAtUtc,
    Guid? OperatingStateEventId,
    string? OperatingStateSourceEventId,
    long? PositionAgeMilliseconds,
    long? OperatingStateAgeMilliseconds,
    bool HasPosition,
    bool PositionIsStale,
    bool OperatingStateIsStale,
    bool IsSimulated,
    bool HasActiveAlarm,
    int ActiveAlarmCount,
    string? MaximumActiveAlarmSeverity,
    IReadOnlyList<SpaceDeviceActiveAlarmDto> ActiveAlarms);

public sealed record SpaceDeviceActiveAlarmDto(
    string AlarmExternalId,
    string AlarmCode,
    string AlarmSeverity,
    string? AlarmMessage,
    DateTimeOffset OccurredAtUtc,
    DateTimeOffset ReceivedAtUtc,
    Guid EventId,
    string SourceEventId,
    long? AgeMilliseconds);
