// <auto-generated />
using System;
using CP6.Core.Services.Plm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP6.Core.Migrations.Plm
{
    [DbContext(typeof(PlmContext))]
    [Migration("20260925150000_PlmWp0Foundation")]
    partial class PlmWp0Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plm")
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmEngineeringBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("EngineeringCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FreezeInputHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("FreezeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FrozenAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("FrozenBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SupersedeInputHash")
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SupersedeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SupersedeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("SupersededBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "FreezeRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmBaseline_Tenant_FreezeRequest");

                    b.HasIndex("TenantId", "SupersedeRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmBaseline_Tenant_SupersedeRequest")
                        .HasFilter("[SupersedeRequestId] IS NOT NULL");

                    b.HasIndex("TenantId", "EngineeringCandidateId", "CandidateVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmBaseline_Tenant_Candidate_Version");

                    b.HasIndex("TenantId", "ManifestId", "EngineeringCandidateId", "CandidateVersion");

                    b.ToTable("EngineeringBaseline", "plm", t =>
                        {
                            t.HasTrigger("TR_PlmBaseline_Protected");

                            t.HasCheckConstraint("CK_PlmBaseline_Digests", "LEN([ManifestDigest])=64 AND [ManifestDigest] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%' AND LEN([FreezeInputHash])=64 AND [FreezeInputHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_PlmBaseline_Status", "[Status] COLLATE Latin1_General_100_BIN2 IN ('FROZEN','SUPERSEDED')");

                            t.HasCheckConstraint("CK_PlmBaseline_SupersedeAudit", "([Status] COLLATE Latin1_General_100_BIN2='FROZEN' AND [SupersededAtUtc] IS NULL AND [SupersededBy] IS NULL AND [SupersedeReason] IS NULL AND [SupersedeRequestId] IS NULL AND [SupersedeInputHash] IS NULL) OR ([Status] COLLATE Latin1_General_100_BIN2='SUPERSEDED' AND [SupersededAtUtc] IS NOT NULL AND [SupersededBy] IS NOT NULL AND [SupersedeReason] IS NOT NULL AND [SupersedeRequestId] IS NOT NULL AND [SupersedeInputHash] IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlmBaseline_Version", "[CandidateVersion] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmEngineeringCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("CandidateVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CurrentManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IterationCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IterationCandidateId", "CandidateKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmCandidate_Tenant_Iteration_Key");

                    b.ToTable("EngineeringCandidate", "plm", t =>
                        {
                            t.HasTrigger("TR_PlmCandidate_Protected");

                            t.HasCheckConstraint("CK_PlmCandidate_Key", "LEN([CandidateKey]) > 0 AND LEN([ProductCd]) > 0");

                            t.HasCheckConstraint("CK_PlmCandidate_Status", "[Status] COLLATE Latin1_General_100_BIN2 IN ('DRAFT','VALIDATED','FROZEN')");

                            t.HasCheckConstraint("CK_PlmCandidate_Version", "[CandidateVersion] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmIterationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IterationKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("IterationVersion")
                        .HasColumnType("int");

                    b.Property<string>("ReviewPackageDigest")
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IterationKey", "IterationVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmIteration_Tenant_Key_Version");

                    b.ToTable("IterationCandidate", "plm", t =>
                        {
                            t.HasTrigger("TR_PlmIteration_Immutable");

                            t.HasCheckConstraint("CK_PlmIteration_Key", "LEN([IterationKey]) > 0");

                            t.HasCheckConstraint("CK_PlmIteration_ReviewDigest", "[ReviewPackageDigest] IS NULL OR (LEN([ReviewPackageDigest]) = 64 AND [ReviewPackageDigest] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%')");

                            t.HasCheckConstraint("CK_PlmIteration_Status", "[Status] COLLATE Latin1_General_100_BIN2 = 'OPEN'");

                            t.HasCheckConstraint("CK_PlmIteration_Version", "[IterationVersion] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmTechnicalManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("CanonicalBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CaptureInputHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("CaptureRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EngineeringCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProductCd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CaptureRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmManifest_Tenant_CaptureRequest");

                    b.HasIndex("TenantId", "EngineeringCandidateId", "CandidateVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmManifest_Tenant_Candidate_Version");

                    b.ToTable("TechnicalManifest", "plm", t =>
                        {
                            t.HasTrigger("TR_PlmManifest_Immutable");

                            t.HasCheckConstraint("CK_PlmManifest_Digests", "LEN([ManifestDigest]) = 64 AND [ManifestDigest] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%' AND LEN([CaptureInputHash]) = 64 AND [CaptureInputHash] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_PlmManifest_Schema", "[SchemaVersion] COLLATE Latin1_General_100_BIN2 = 'plm-technical-manifest-v1' AND DATALENGTH([CanonicalBytes]) > 0");

                            t.HasCheckConstraint("CK_PlmManifest_Version", "[CandidateVersion] > 0 AND [ItemCount] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmTechnicalManifestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CapturedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("ItemCanonicalBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ItemDigest")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialCd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProcessCd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ProductCd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int?>("SemanticSortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceOwnerType")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<byte[]>("SourceRowVersion")
                        .HasColumnType("varbinary(8)");

                    b.Property<string>("TaskCd")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ManifestId", "ItemType", "IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmItem_Tenant_Manifest_Type_Identity");

                    b.HasIndex("TenantId", "ManifestId", "ItemType", "SemanticSortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_PlmItem_Tenant_Manifest_Type_SortOrder")
                        .HasFilter("[SemanticSortOrder] IS NOT NULL");

                    b.ToTable("TechnicalManifestItem", "plm", t =>
                        {
                            t.HasTrigger("TR_PlmItem_Immutable");

                            t.HasCheckConstraint("CK_PlmItem_Bytes", "DATALENGTH([ItemCanonicalBytes]) > 0 AND LEN([IdentityKey]) > 0");

                            t.HasCheckConstraint("CK_PlmItem_Digest", "LEN([ItemDigest]) = 64 AND [ItemDigest] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_PlmItem_Type", "([ItemType] COLLATE Latin1_General_100_BIN2='PRODUCT' AND [SourceOwnerType] COLLATE Latin1_General_100_BIN2='ProductMaster' AND [ProcessCd] IS NULL AND [MaterialCd] IS NULL AND [TaskCd] IS NULL AND [SemanticSortOrder] IS NULL) OR ([ItemType] COLLATE Latin1_General_100_BIN2='BOM' AND [SourceOwnerType] COLLATE Latin1_General_100_BIN2='ProductMaterial' AND [ProcessCd] IS NOT NULL AND [MaterialCd] IS NOT NULL AND [TaskCd] IS NULL AND [SemanticSortOrder]>0) OR ([ItemType] COLLATE Latin1_General_100_BIN2='ROUTING' AND [SourceOwnerType] COLLATE Latin1_General_100_BIN2='ProductProcess' AND [ProcessCd] IS NULL AND [MaterialCd] IS NULL AND [TaskCd] IS NOT NULL AND [SemanticSortOrder]>0)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmEngineeringBaseline", b =>
                {
                    b.HasOne("CP6.Entity.DomainModels.Plm.PlmEngineeringCandidate", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EngineeringCandidateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP6.Entity.DomainModels.Plm.PlmTechnicalManifest", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ManifestId", "EngineeringCandidateId", "CandidateVersion")
                        .HasPrincipalKey("TenantId", "Id", "EngineeringCandidateId", "CandidateVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmEngineeringCandidate", b =>
                {
                    b.HasOne("CP6.Entity.DomainModels.Plm.PlmIterationCandidate", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "IterationCandidateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmTechnicalManifest", b =>
                {
                    b.HasOne("CP6.Entity.DomainModels.Plm.PlmEngineeringCandidate", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EngineeringCandidateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CP6.Entity.DomainModels.Plm.PlmTechnicalManifestItem", b =>
                {
                    b.HasOne("CP6.Entity.DomainModels.Plm.PlmTechnicalManifest", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ManifestId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
