// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msbb.Infrastructure.Persistence;

#nullable disable

namespace Msbb.Infrastructure.Migrations
{
    [DbContext(typeof(MsbbDbContext))]
    [Migration("20251127142234_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Msbb.Domain.Entities.GeneralMaster", b =>
                {
                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NumValue1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Value1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClassCode", "Code");

                    b.ToTable("M_GENERAL");

                    b.HasData(
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "01",
                            DisplayOrder = 1,
                            Name = "個"
                        },
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "02",
                            DisplayOrder = 2,
                            Name = "枚"
                        },
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "03",
                            DisplayOrder = 3,
                            Name = "式"
                        });
                });

            modelBuilder.Entity("Msbb.Domain.Entities.SysLog", b =>
                {
                    b.Property<long>("LogSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogSeq"));

                    b.Property<string>("BaseCD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LoginID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LogSeq");

                    b.ToTable("T_SYS_LOG");
                });

            modelBuilder.Entity("Msbb.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("MajorCategoryNO")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("FunctionNO")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("DelFlg")
                        .HasColumnType("bit");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FunctionID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsUsrID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MajorCategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdUsrID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MajorCategoryNO", "FunctionNO");

                    b.ToTable("T_SYS_MENU");
                });
#pragma warning restore 612, 618
        }
    }
}
