// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msbb.Infrastructure.Persistence;

#nullable disable

namespace Msbb.Infrastructure.Migrations
{
    [DbContext(typeof(MsbbDbContext))]
    partial class MsbbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Msbb.Domain.Entities.GeneralMaster", b =>
                {
                    b.Property<string>("ClassCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<bool>("DelFlg")
                        .HasColumnType("bit");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsUsrID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NumValue1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdUsrID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClassCode", "Code");

                    b.ToTable("M_GENERAL");

                    b.HasData(
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "01",
                            DelFlg = false,
                            DisplayOrder = 1,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8696),
                            InsUsrID = "SYSTEM",
                            Name = "個"
                        },
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "02",
                            DelFlg = false,
                            DisplayOrder = 2,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8699),
                            InsUsrID = "SYSTEM",
                            Name = "枚"
                        },
                        new
                        {
                            ClassCode = "UNIT",
                            Code = "03",
                            DelFlg = false,
                            DisplayOrder = 3,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8700),
                            InsUsrID = "SYSTEM",
                            Name = "式"
                        },
                        new
                        {
                            ClassCode = "DATA_STATUS",
                            Code = "0",
                            DelFlg = false,
                            DisplayOrder = 10,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8701),
                            InsUsrID = "SYSTEM",
                            Name = "未登録/新規"
                        },
                        new
                        {
                            ClassCode = "DATA_STATUS",
                            Code = "1",
                            DelFlg = false,
                            DisplayOrder = 20,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8702),
                            InsUsrID = "SYSTEM",
                            Name = "承認待ち"
                        },
                        new
                        {
                            ClassCode = "DATA_STATUS",
                            Code = "9",
                            DelFlg = false,
                            DisplayOrder = 30,
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8703),
                            InsUsrID = "SYSTEM",
                            Name = "承認済/確定"
                        });
                });

            modelBuilder.Entity("Msbb.Domain.Entities.SysLog", b =>
                {
                    b.Property<long>("LogSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogSeq"));

                    b.Property<string>("BaseCD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LoginID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LogSeq");

                    b.ToTable("T_SYS_LOG");
                });

            modelBuilder.Entity("Msbb.Domain.Entities.SysMenu", b =>
                {
                    b.Property<int>("MajorCategoryNO")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("FunctionNO")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("DelFlg")
                        .HasColumnType("bit");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FunctionID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("InsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsUsrID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MajorCategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdUsrID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MajorCategoryNO", "FunctionNO");

                    b.ToTable("T_SYS_MENU");

                    b.HasData(
                        new
                        {
                            MajorCategoryNO = 10,
                            FunctionNO = 10,
                            DelFlg = false,
                            DisplayOrder = 10,
                            FunctionID = "MSBBPA010",
                            FunctionName = "見積計算書入力",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8575),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "見積・报价",
                            Url = "/estimate/input"
                        },
                        new
                        {
                            MajorCategoryNO = 10,
                            FunctionNO = 20,
                            DelFlg = false,
                            DisplayOrder = 20,
                            FunctionID = "MSBBPA020",
                            FunctionName = "見積計算書一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8577),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "見積・报价",
                            Url = "/estimate/list"
                        },
                        new
                        {
                            MajorCategoryNO = 10,
                            FunctionNO = 30,
                            DelFlg = false,
                            DisplayOrder = 30,
                            FunctionID = "MSBBPA030",
                            FunctionName = "御見積書登録・発行",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8579),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "見積・报价",
                            Url = "/quote/input"
                        },
                        new
                        {
                            MajorCategoryNO = 10,
                            FunctionNO = 40,
                            DelFlg = false,
                            DisplayOrder = 40,
                            FunctionID = "MSBBPA040",
                            FunctionName = "御見積書一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8581),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "見積・报价",
                            Url = "/quote/list"
                        },
                        new
                        {
                            MajorCategoryNO = 20,
                            FunctionNO = 10,
                            DelFlg = false,
                            DisplayOrder = 10,
                            FunctionID = "MSBBPA070",
                            FunctionName = "受注入力",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8583),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "受注管理",
                            Url = "/order/input"
                        },
                        new
                        {
                            MajorCategoryNO = 20,
                            FunctionNO = 20,
                            DelFlg = false,
                            DisplayOrder = 20,
                            FunctionID = "MSBBPA080",
                            FunctionName = "受注一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8584),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "受注管理",
                            Url = "/order/list"
                        },
                        new
                        {
                            MajorCategoryNO = 20,
                            FunctionNO = 30,
                            DelFlg = false,
                            DisplayOrder = 30,
                            FunctionID = "MSBBPA090",
                            FunctionName = "単価訂正",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8586),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "受注管理",
                            Url = "/order/price-correction"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 10,
                            DelFlg = false,
                            DisplayOrder = 10,
                            FunctionID = "MSBBPA050",
                            FunctionName = "製品マスタ",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8588),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/product-input"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 20,
                            DelFlg = false,
                            DisplayOrder = 20,
                            FunctionID = "MSBBPA060",
                            FunctionName = "製品マスタ一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8589),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/product-list"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 30,
                            DelFlg = false,
                            DisplayOrder = 30,
                            FunctionID = "MSBBPA110",
                            FunctionName = "取引先マスタ",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8591),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/bp-input"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 40,
                            DelFlg = false,
                            DisplayOrder = 40,
                            FunctionID = "MSBBPA120",
                            FunctionName = "取引先マスタ一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8593),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/bp-list"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 50,
                            DelFlg = false,
                            DisplayOrder = 50,
                            FunctionID = "MSBBPA130",
                            FunctionName = "シート単価マスタ",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8594),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/sheet-price"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 60,
                            DelFlg = false,
                            DisplayOrder = 60,
                            FunctionID = "MSBBPA140",
                            FunctionName = "版型・木型マスタ",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8596),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/die-input"
                        },
                        new
                        {
                            MajorCategoryNO = 30,
                            FunctionNO = 70,
                            DelFlg = false,
                            DisplayOrder = 70,
                            FunctionID = "MSBBPA150",
                            FunctionName = "版型・木型マスタ一覧照会",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8598),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "マスタ管理",
                            Url = "/master/die-list"
                        },
                        new
                        {
                            MajorCategoryNO = 99,
                            FunctionNO = 10,
                            DelFlg = false,
                            DisplayOrder = 10,
                            FunctionID = "MSBBPA100",
                            FunctionName = "FSCチェックシート出力",
                            InsDate = new DateTime(2025, 11, 27, 22, 45, 16, 924, DateTimeKind.Local).AddTicks(8599),
                            InsUsrID = "SYSTEM",
                            MajorCategoryName = "帳票出力",
                            Url = "/report/fsc-output"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
