<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CP6.Space.Infrastructure\CP6.Space.Infrastructure.csproj" />
    <ProjectReference Include="..\CP6.Space.CadWorker.AutoCadCandidate\CP6.Space.CadWorker.AutoCadCandidate.csproj" />
  </ItemGroup>
</Project>
