apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cp6-kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "{appID}"
    - name: clientID
      value: "{appID}"
    - name: authType
      value: "none"
    - name: disableTls
      value: "true"
    - name: initialOffset
      value: "oldest"
    - name: escapeHeaders
      value: "false"
    - name: excludeHeaderMetaRegex
      value: "(?i)^(__(key|topic|partition|offset|timestamp)|pubsubname)$"
    - name: maxMessageBytes
      value: "1048576"
scopes:
  - cp6-c02-publisher
  - cp6-c02-receiver
